# Description:
# ------------
# This playbook is used to build the binary from the source code.
# The build itself is managed via a Makefile.
# Before a new build the old one is cleaned.

---
- name: Playbook to build binary from the source code..
  hosts: localhost
  become: false
  tasks:
    - name: Clena build..
      ansible.builtin.command:
        cmd: make -C .. clean

    - name: Build..
      ansible.builtin.command:
        cmd: make -C .. build
