# Description:
# ------------
# This playbook is used to deploy the service to the RHEL9 systemd service.
# The service is deployed using the systemd service file.
# The service is started and enabled.
# The service is deployed with the certificates from the <project>/resources/certificates folder. 
# The certificates are copied to the /var/certificates/<service_url> folder.
# The service is deployed with the binary from the <project>/build folder.
# The binary is copied to the /usr/local/bin/<service_name> folder.
# The SELinux context is set to bin_t for the binary.
#

---
- name: Deploy service to the RHEL9 systemd service..
  hosts: bastion
  become: true
  gather_facts: no

  vars:
    service_name: "links"
    build_binary: "../build/{{ service_instance_name }}"
    installation_path: "/usr/local/bin"
    installation_file: "{{ installation_path }}/{{ service_instance_name }}"
    systemd_service_file: "../chome/etc/systemd/system/{{ service_instance_name }}.service"
    systemd_service_template_file: "../chome/etc/systemd/system/{{ service_name }}.service.j2"
    datafile_path: "/var/lib/{{ service_instance_name }}"

    resources_path: "../resources"
    resources_certificates_path: "{{ resources_path }}/certificates/{{ service_instance_url }}"
    certificates_path: "/var/certificates/{{ service_instance_url }}"
    certificate_file: "cert.pem"
    key_file: "privkey.pem"

  tasks:
    - name: Render the systemd service file template and save to file..
      template:
        src: "{{ systemd_service_template_file }}"
        dest: "/etc/systemd/system/{{ service_instance_name }}.service"

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Deploy binary from previously create build..
      ansible.builtin.copy:
        src: "{{ build_binary }}"
        dest: "{{ installation_file }}"
        mode: '0755'
        owner: root
        group: root

    - name: Create folder for data file..
      ansible.builtin.file:
        path: "{{ datafile_path }}"
        state: directory
        mode: "0755"

    - name: Deploy links.csv file with data..
      ansible.builtin.copy:
        src: "{{ resources_path }}/links.csv"
        dest: "{{ datafile_path }}/links.csv"
        mode: '0644'
        owner: root
        group: root

    - name: Set SELinux context to bin_t..
      ansible.builtin.command:
        cmd: semanage fcontext -a -t bin_t "{{ installation_file }}"

    - name: Apply SELinux context changes
      ansible.builtin.command:
        cmd: restorecon -v "{{ installation_file }}"

    - name: Create certificate resource folder..
      ansible.builtin.file:
        path: "{{ resources_certificates_path }}"
        state: directory
        mode: "0755"
    
    - name: Check if resource for certificates exists..
      stat:
        path: "{{ resources_certificates_path }}/{{ certificate_file }}"
      register: cert_file
      delegate_to: localhost

    - name: certificate file existence..
      debug:
        msg: >
          The certificate file exists at {{ cert_file.stat.path }}
          with size {{ cert_file.stat.size }} bytes.
      when: cert_file.stat.exists

    - name: Fail if the certificate file does not exist..
      fail:
        msg: >
          "The certificate file does not exist!"
          "{{ resources_certificates_path }}/{{ certificate_file }}"
      when: not cert_file.stat.exists

    - name: "01 - 01 - Deploy certificates, Create certificates folder.."
      ansible.builtin.file:
        path: "{{ certificates_path }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: "01 - 02 - Deploy certificates, Copy certificate file.."
      ansible.builtin.copy:
        src: "{{ resources_certificates_path }}/{{ certificate_file }}"
        dest: "{{ certificates_path }}"
        mode: "0644"
        owner: root
        group: root
      
    - name: "01 - 03 - Deploy certificates, Copy private key file.."
      ansible.builtin.copy:
        src: "{{ resources_certificates_path }}/{{ key_file }}"
        dest: "{{ certificates_path }}"
        mode: "0644"
        owner: root
        group: root
    
    - name: "01 - 04 - Deploy certificates, Copy fullchain file.."
      ansible.builtin.copy:
        src: "{{ resources_certificates_path }}/fullchain.pem"
        dest: "{{ certificates_path }}"
        mode: "0644"
        owner: root
        group: root
    
    - name: Stop the service..
      ansible.builtin.systemd:
        name: "{{ service_instance_name }}.service"
        state: stopped
        enabled: yes

    - name: Start service
      ansible.builtin.systemd:
        name: "{{ service_instance_name }}.service"
        state: started
        enabled: yes
