# Description:
# ------------
# This playbook is used to get certificates from Let's Encrypt host.
# The certificates are stored in the <project>/resources/certificates folder.
# The certificates are used to deploy the service via deploy.yaml playbook.
#
# Usage:
# ------
# 1. On the Let's Encrypt host use `build_resource.yaml` playbook to copy the certificates to the resources folder on the host where the service is deployed.
# 2. On the host where the service is deployed use this `get_certificates.yaml` and then `deploy.yaml` playbook to deploy the service.
#    Use `hosts: localhost` in the playbook to declare where to execute this playbook if it's not the `localhost`.
#
# ```bash
# $ cd <project>/playbooks
# $ ansible-playbook get_certificates.yaml
# ```
#
# Note:
# -----
# - Correct the letsencrypt_host and ssh_user variables..
# - Correct the certificate_ulrs for your service URL..
#
# Additional info:
# ----------------
# - It is not possible to copy the certificates directly from the /etc/letsencrypt/live folder because the folder is owned by the root.
# - The certificates are copied to the resources folder with privileges for the resource owner and group and prepared to be used as a resource via the get_certificates.yaml playbook first.
---
- name: Get certificates from Let's Encrypt host..
  hosts: localhost
  become: false
  gather_facts: no
  vars:
    letsencrypt_host: "bastion.example.com"
    ssh_user: "lucifer"
    letsencrypt_resource_path: "/var/resources/certificates"
    certificate_urls:
      - links.example.com
    resources_path: "../resources"
    resources_certificates_path: "{{ resources_path }}/certificates"
    certificate_files:
      - "cert.pem"
      - "privkey.pem"
      - "chain.pem"
      - "fullchain.pem"
  tasks:
    - name: Create certificates directory..
      file:
        path: "{{ resources_certificates_path }}"
        state: directory
        recurse: yes
    
    - name: Print certificate URLs..
      debug:
        msg: "Source: `{{ letsencrypt_resource_path }}/{{ item }}`   Destination: `{{ resources_certificates_path }}`"
      with_items: "{{ certificate_urls }}"

    - name: Copy certificate resources from Let's Encrypt host..
      ansible.builtin.command: 
        cmd: "scp  {{ ssh_user }}@{{ letsencrypt_host }}:{{ letsencrypt_resource_path }}/{{ item[0] }}/{{ item[1] }} {{ resources_certificates_path }}"
      with_nested:
        - "{{ certificate_urls }}"
        - "{{ certificate_files }}"
